# This file is part of the dune-xt-common project:
#   https://github.com/dune-community/dune-xt-common
# Copyright 2009-2017 dune-xt-functions developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
#          with "runtime exception" (http://www.dune-project.org/license.html)
# Authors:
#   Felix Schindler (2016 - 2017)
#   Rene Milk       (2016 - 2017)
#   Tobias Leibner  (2016)

sudo: required
dist: trusty
language: generic
services: docker

before_script:
    - export IMAGE="renemilk/travis-speedtest:latest"
    # get image with fallback to master branch of the super repo
    - docker pull ${IMAGE}
    - export DOCKER_RUN="docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ ${IMAGE}"

install:
    - sudo apt-get update && sudo apt-get install -y hdparm fio

script:
    - travis_wait 21 sudo ${DOCKER_RUN} /root/src/test.bash
    - travis_wait 21 sudo ./test.bash


notifications:
  email:
    on_success: change
    on_failure: change

branches:
  except:
    - gh-pages
